#此工作流将使用节点运行测试，然后在创建发布时将包发布到GitHub包
#有关详细信息，请参阅： https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

姓名: Node.js包

在……之上:
释放:
类型: [创造]

工作:
建立:
连续的: Ubuntu-最新
步骤:
-uses: 操作/结帐@v4
-uses: 操作/设置-节点@v4
和……一起:
节点版本: 20
-跑: npm ci
-跑: npm测试

publish-gpr:
需要: 建立
连续的: Ubuntu-最新
权限:
内容: 读
包: 写
步骤:
-uses: 操作/结帐@v4
-uses：操作/设置-节点@v4
-uses：操作/设置-节点@v4:
节点版本: 20
registry-url: HTTPS://npm.pkg.github.com/
-运行：npm cirun: npm ci
PM ci:nPM发布
env:
NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
